# Generated by Django 2.2.17 on 2021-03-06 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ExerciseID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=500)),
                ('Difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('DemoImage', models.ImageField(blank=True, upload_to='exercise_images')),
                ('DemoVideo', models.URLField(blank=True)),
                ('Date', models.DateField()),
                ('Likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('SetID', models.AutoField(primary_key=True, serialize=False)),
                ('NoOfReps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ExerciseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrkout.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('ProfilePicture', models.ImageField(blank=True, upload_to='profile_images')),
                ('LikedExercises', models.ManyToManyField(to='wrkout.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('WorkoutID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Likes', models.IntegerField(default=0)),
                ('CreatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrkout.User')),
                ('Sets', models.ManyToManyField(to='wrkout.Set')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='LikedWorkouts',
            field=models.ManyToManyField(to='wrkout.Workout'),
        ),
        migrations.AddField(
            model_name='user',
            name='SavedWorkouts',
            field=models.ManyToManyField(related_name='user_requests_created', to='wrkout.Workout'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='CreatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrkout.User'),
        ),
    ]
