# Generated by Django 2.2.17 on 2021-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='SavedWorkouts',
            field=models.ManyToManyField(related_name='userSaved', to='wrkout.Workout'),
        ),
    ]
