# Generated by Django 2.2.17 on 2021-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkout', '0003_auto_20210310_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='Slug',
            field=models.SlugField(unique=True),
        ),
    ]
