# Generated by Django 2.2.17 on 2021-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkout', '0005_auto_20210310_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DislikedExercises',
            field=models.ManyToManyField(to='wrkout.Exercise'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='DislikedWorkouts',
            field=models.ManyToManyField(to='wrkout.Workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LikedExercises',
            field=models.ManyToManyField(related_name='Likeduserprofile', to='wrkout.Exercise'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LikedWorkouts',
            field=models.ManyToManyField(related_name='Likeduserprofile', to='wrkout.Workout'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='SavedWorkouts',
            field=models.ManyToManyField(related_name='Saveduserprofile', to='wrkout.Workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
