# Generated by Django 2.2.17 on 2021-03-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrkout', '0006_auto_20210331_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='ExerciseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrkout.Exercise'),
        ),
    ]
